use lakochi;
drop table food;
create table food (fno int(3) Primary key,fname varchar(50),type varchar(20),price int(5));
insert into food values(001,'Parippu Vada','Veg',8);
insert into food values(002,'Cutlet','Veg',12);
insert into food values(003,'Banana Fry','Veg',8);
insert into food values(004,'Thayir Vadai','Veg',12);
insert into food values(005,'Uzhunnu Vada','Veg',8);
insert into food values(006,'Porotta','Veg',10);
insert into food values(007,'Chapathi','Veg',5);
insert into food values(008,'Appom','Veg',10);
insert into food values(009,'Onion Uthappam','Veg',12);
insert into food values(010,'Plain Dosa','Veg',10);
insert into food values(011,'Ghee Dosa','Veg',70);
insert into food values(012,'Masala Dosa','Veg',70);
insert into food values(013,'Lemon Rice','Veg',60);
insert into food values(014,'Jeera Rice','Veg',60);
insert into food values(015,'Curd Rice','Veg',60);
insert into food values(016,'Veg Biriyani','Veg',100);
insert into food values(017,'Veg Fried Rice','Veg',100);
insert into food values(018,'Mixed Fried Rice','Non Veg',140);
insert into food values(019,'Chicken Fried Rice','Non Veg',120);
insert into food values(020,'Chicken Biriyani','Non Veg',120);
insert into food values(021,'Mutton Biriyani','Non Veg',130);
insert into food values(022,'Garlic Naan','Veg',15);
insert into food values(023,'Butter Naan','Veg',15);
insert into food values(024,'Chicken Curry','Non Veg',100);
insert into food values(025,'Chicken Fry','Non Veg',140);
insert into food values(026,'Chicken 65','Non Veg',150);
insert into food values(027,'Chicken Chettinad','Non Veg',140);
insert into food values(028,'Dragon Chicken','Non Veg',180);
insert into food values(029,'Chicken Lollipops','Non Veg',160);
insert into food values(030,'Chilly Chicken','Non Veg',150);
insert into food values(031,'Chicken Tikka Masala','Non Veg',170);
insert into food values(032,'Butter Chicken','Non Veg',180);
insert into food values(033,'Fish Curry','Non Veg',120);
insert into food values(034,'Fish Fry','Non Veg',140);
insert into food values(035,'Fish Special','Non Veg',170);
insert into food values(036,'Beef Roast','Non Veg',160);
insert into food values(037,'Beef fry','Non Veg',180);
insert into food values(038,'Beef curry','Non Veg',150);
insert into food values(039,'Al-faham','Non Veg',200);
insert into food values(040,'Shawarma','Non Veg',120);
insert into food values(041,'Chicken Porotta Roll','Non Veg',100);
insert into food values(042,'Beef Porotta Roll','Non Veg',120);
insert into food values(043,'Sheshwan Chicken Noodles','Non Veg',120);
insert into food values(044,'Veg Noodles','Veg',100);
insert into food values(045,'Malai Koftha','Veg',120);
insert into food values(046,'Chilly Goby','Veg',120);
insert into food values(047,'Alu Mattar','Veg',100);
insert into food values(048,'Dal Makhni','Veg',80);
insert into food values(049,'Channa Masala','Veg',120);
insert into food values(050,'Raitha','Veg',30);
insert into food values(051,'Garlic Mushroom','Veg',100);
insert into food values(052,'Chiken Vindaaloo','Non Veg',200);
insert into food values(053,'Grilled Paneer','Veg',120);
insert into food values(054,'Moong Dal','Veg',80);
insert into food values(055,'Stew','Veg',50);
insert into food values(056,'Rajma','Veg',80);
insert into food values(057,'Goby Manchurian','Veg',120);
insert into food values(058,'Aloo Goby','Veg',120);
insert into food values(059,'Kadai Paneer','Veg',120);
insert into food values(060,'Chilly Panner','Veg',130);
insert into food values(061,'Paneer Butter Masala','Veg',140);
insert into food values(062,'Egg Roast','Non Veg',110);
insert into food values(063,'Lasagna','Non Veg',240);
insert into food values(064,'Chocolate Shake','Veg',60);
insert into food values(065,'Vanilla Shake','Veg',60);
insert into food values(066,'Strawberry Shake','Veg',60);
insert into food values(067,'Butterscotch Shake','Veg',60);
insert into food values(068,'Orange Juice','Veg',40);
insert into food values(069,'Watermelon Juice','Veg',40);
insert into food values(070,'Grape Juice','Veg',40);
insert into food values(071,'Lime Juice','Veg',30);
insert into food values(072,'Lime Soda','Veg',40);
insert into food values(073,'Musambi Juice','Veg',40);
insert into food values(074,'Pineapple Juice','Veg',40);
insert into food values(075,'Water','Veg',20);
insert into food values(076,'Green Tea','Veg',30);
insert into food values(077,'Lemon Tea','Veg',30);
insert into food values(078,'Tea','Veg',10);
insert into food values(079,'Coffee','Veg',20);
insert into food values(080,'Capuccino','Veg',60);
insert into food values(081,'Tomato Soup','Veg',75);
insert into food values(082,'Musroom Soup','Veg',75);
insert into food values(083,'Baby Corn Soup','Veg',75);
select * from food;